### ISSUE TITLE
Minor issue: B3LYP functional flavors clarification

### ISSUE THREAD

**Issue by aka-Marlen** [Open-Quantum-Platform/openqp#23]
Dear OpenQP team,

in the description of the keyword "[input]functional" (https://github.com/Open-Quantum-Platform/openqp/wiki/INPUT) a standard list of functionals contains B3LYP, when trying to run a job with this exact parameter, LibXC returns an error:
" The information about selected functionals:
B3LYP functional has different meanings,
so that it can not be run using LibXC interface.
For running B3LYP, choose one of them:
 - B3LYPV1R with  VWN RPA LDA correlation part (default for Gaussian)
 - B3LYPV3  with  VWN_3   LDA correlation part
 - B3LYPV5  with  VWN_5   LDA correlation part (default for GAMESS-US)
Aborting from LibXC interface..."

It would be nice to mention this on the documentation page or to have some default B3LYP flavour selected during input checking (with the corresponding warning).

Example is attached
[b3lyp_flavors.zip](https://github.com/user-attachments/files/17851483/b3lyp_flavors.zip)

**Comment by Alireza-Lashkaripour** [comment]
Dear @aka-Marlen,

Thank you so much for your message, we will mention the B3LYP description one documentation page.


Cheers,
-Alireza
