### ISSUE TITLE
How update Supervisor

### ISSUE THREAD

**Issue by Kruikie349** [Open-Quantum-Platform/openqp#33]
I reinstalled HA on my mini pc Generic x86-64 but I can't restore my last full backup. An older version worked. i don't have backups from supervisors When I try to load the latest version I get this:

**Backup was made on supervisor version 2024.11.5.dev2601, can't restore on 2024.11.4. Must update supervisor first.**

instal: 
Core 2024.11.3
Supervisor 2024.11.4
Operating System 13.2
Frontend 20241106.2

I searched on github but I don't understand it.
on https://github.com/home-assistant/supervisor/releases
I can't see a   .tar  file for Generic x86-64 

Can someone help me?

**Comment by foxtran** [comment]
This issue is not related to OQP.
