### ISSUE TITLE
json format as output

### ISSUE THREAD

**Issue by stecrespi** [Open-Quantum-Platform/openqp#36]
Dear developers, I can see that it would be possible to produce JSON files as an output of the calculations. Is there a way to select such an option explicitly in the runs and have the JSON produced alongside logs and molden, or is this still under active development?
Thank you!
Stefano

**Comment by Alireza-Lashkaripour** [comment]
Dear @stecrespi 

Of course, it is possible. Please check this wiki page: https://github.com/Open-Quantum-Platform/openqp/wiki/Initial%20Guess%20Options

**Comment by stecrespi** [comment]
Thank you so much! 👍
